export const awards = {
  eyebrow: "Awards",
  heading: "Recognition for launch systems",
  ariaLabel: "Award recognitions",
  certificateLabel: "Certificate placeholder",
  items: [
    {
      platform: "Awwwards",
      project: "Atlas Grid",
      prize: "Site of the Day",
      date: "Aug 18, 2026",
      accent: "var(--brand-light)",
    },
    {
      platform: "The FWA",
      project: "Nimbus Cloud",
      prize: "FWA of the Day",
      date: "Jul 12, 2026",
      accent: "#1f7fb8",
    },
    {
      platform: "CSSDA",
      project: "Orbit Pay",
      prize: "Website of the Day",
      date: "May 22, 2026",
      accent: "#ffffff",
    },
    {
      platform: "Awwwards",
      project: "Forma Lab",
      prize: "Honorable Mention",
      date: "Mar 04, 2026",
      accent: "var(--brand-light)",
    },
    {
      platform: "CSSDA",
      project: "Signal One",
      prize: "UX Design Award",
      date: "Nov 19, 2025",
      accent: "#1f7fb8",
    },
    {
      platform: "The FWA",
      project: "Brightpath",
      prize: "Mobile Excellence",
      date: "Oct 07, 2025",
      accent: "#ffffff",
    },
    {
      platform: "Awwwards",
      project: "Coredesk",
      prize: "Developer Award",
      date: "Sep 15, 2025",
      accent: "var(--brand-light)",
    },
    {
      platform: "CSSDA",
      project: "Northline",
      prize: "Innovation Award",
      date: "Jun 28, 2025",
      accent: "#1f7fb8",
    },
  ],
} as const;
