export const roi = {
  id: "roi",
  eyebrow: "Rekenen",
  heading: "Wat levert automatisering jou op?",
  intro: "Schuif de waarden naar jouw situatie. De uitkomst rekent live mee.",
  fields: {
    hours: {
      id: "hours",
      label: "Uren per week aan repetitief werk",
      min: 1,
      max: 40,
      step: 1,
      default: 12,
      suffix: "u",
    },
    rate: {
      id: "rate",
      label: "Gemiddeld uurtarief",
      min: 25,
      max: 250,
      step: 5,
      default: 65,
      prefix: "EUR",
    },
    people: {
      id: "people",
      label: "Aantal betrokken medewerkers",
      min: 1,
      max: 50,
      step: 1,
      default: 4,
      suffix: "fte",
    },
    automation: {
      id: "automation",
      label: "Geschat automatiseringspercentage",
      min: 20,
      max: 90,
      step: 5,
      default: 65,
      suffix: "%",
    },
  },
  outputs: {
    monthly: { label: "Besparing per maand" },
    yearly: { label: "Besparing per jaar" },
    payback: { label: "Terugverdientijd", suffix: "maanden" },
    hoursFreed: { label: "Vrijgekomen uren per jaar", suffix: "u" },
  },
  chart: {
    label: "Kosten over twaalf maanden",
    months: 12,
    legend: {
      without: "Zonder automatisering",
      with: "Met automatisering",
    },
    crossingLabel: "Break-even",
    noCrossingLabel: "Break-even valt na maand 12",
    axisLabel: "Maand",
  },
  assumptions: {
    title: "Aannames achter deze som",
    toggleOpen: "Toon aannames",
    toggleClose: "Verberg aannames",
    items: [
      "Een maand telt 4,33 werkweken.",
      "De bouwkosten schalen mee met het aantal betrokken medewerkers en het automatiseringspercentage.",
      "Naast de bouw rekenen we maandelijkse kosten voor hosting, modelgebruik en beheer.",
      "Vrijgekomen uren gaan naar werk dat wel oplevert; ze zijn hier gewaardeerd tegen het ingevulde uurtarief.",
      "Alle bedragen zijn exclusief btw en indicatief, geen offerte.",
    ],
  },
  share: {
    label: "Deel deze berekening",
    copy: "Kopieer link",
    copied: "Link gekopieerd",
  },
  bridge: {
    question: "Klopt dit voor jouw situatie?",
    body: "Stel je eigen agent samen en zie welke flow erbij hoort.",
    cta: "Naar de configurator",
    href: "#configurator",
  },
} as const;
